import io

import pandas as pd
from fpdf import FPDF, XPos, YPos


def _pdf_safe(text: str) -> str:
    text = text.replace("₹", "Rs. ")
    return text.encode("latin-1", errors="ignore").decode("latin-1")


def _line(pdf, text):
    pdf.multi_cell(0, 7, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def build_pdf_report(symbol, market, latest_price_fmt, change_pct, signal, score,
                      risk, forecast_7d, forecast_7d_fmt, summary_text) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, _pdf_safe(f"Stock Report: {symbol} ({market})"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "", 11)
    pdf.ln(2)
    _line(pdf, _pdf_safe(f"Latest price: {latest_price_fmt} | Change: {change_pct:+.2f}%"))
    _line(pdf, _pdf_safe(f"AI Signal: {signal} (score {score:+d}/100)"))
    _line(pdf, _pdf_safe(f"Risk: {risk['risk_label']} | Annual volatility: {risk['annual_volatility_pct']}% | Max drawdown: {risk['max_drawdown_pct']}%"))
    if risk.get("beta") is not None:
        _line(pdf, _pdf_safe(f"Beta vs index: {risk['beta']}"))

    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "7-Day Forecast", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 11)
    for i, val in enumerate(forecast_7d_fmt, start=1):
        pdf.cell(0, 7, _pdf_safe(f" Day {i}: {val}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "AI Market Summary", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 11)
    _line(pdf, _pdf_safe(summary_text.replace("**", "")))

    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    _line(pdf, "Generated by the Stock Prediction Dashboard. Not financial advice.")

    return bytes(pdf.output())


def build_excel_report(symbol, history_df: pd.DataFrame, indicators_df: pd.DataFrame,
                        forecast_df: pd.DataFrame) -> bytes:
    buffer = io.BytesIO()
    with pd.ExcelWriter(buffer, engine="openpyxl") as writer:
        history_df.to_excel(writer, sheet_name="Price History")
        indicators_df.to_excel(writer, sheet_name="Indicators")
        forecast_df.to_excel(writer, sheet_name="Forecast", index=False)
    return buffer.getvalue()
